logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java_auto_test
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.module
  mapper-locations: mapper/*

